/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package netimapct;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.PreparedStatement;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.sql.ResultSet;
import java.util.HashSet;
import java.util.Set;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.JTabbedPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
/**
/**
 *
 * @author mohab
 */
public class admindashboard extends javax.swing.JFrame {

    /**
     * Creates new form admindashboard
     */
    Connection con;
    String cuurentusername;
    public admindashboard(String logged_Username) {
        initComponents();
        cuurentusername = logged_Username;
        welcomeuser.setText(cuurentusername);
        this.setLocationRelativeTo(null);
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/netpackt","root","0238736729@nN");
        } catch (SQLException ex) {
            Logger.getLogger(login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        current_username.setText(cuurentusername);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        gender = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        viewUsers_menubtn = new javax.swing.JButton();
        rigsterAdmins_menubtn = new javax.swing.JButton();
        registerUsers_menubtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        welcomeuser = new javax.swing.JLabel();
        communications_menubtn = new javax.swing.JButton();
        viewAdmins_menubtn = new javax.swing.JButton();
        logout_menubtn = new javax.swing.JButton();
        settings_menubtn = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        register_adminbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        username_admin = new javax.swing.JTextField();
        password_admin = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        user_registerbtn = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        userName_reg = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        useremail_reg = new javax.swing.JTextField();
        male_rbtn = new javax.swing.JRadioButton();
        female_rbtn = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        password_reg = new javax.swing.JPasswordField();
        password2_input = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        users_table = new javax.swing.JTable();
        jButton6 = new javax.swing.JButton();
        userid_input = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        admins_table = new javax.swing.JTable();
        viewadmins_btn = new javax.swing.JButton();
        deleteadmin_btn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        adminid_input = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        current_username = new javax.swing.JTextField();
        update_adminpassbtn = new javax.swing.JButton();
        delete_adminbtn = new javax.swing.JButton();
        current_password = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jPanel4.setBackground(new java.awt.Color(213, 235, 226));

        viewUsers_menubtn.setText("View Users");
        viewUsers_menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewUsers_menubtnActionPerformed(evt);
            }
        });

        rigsterAdmins_menubtn.setText("Register Admins");
        rigsterAdmins_menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rigsterAdmins_menubtnActionPerformed(evt);
            }
        });

        registerUsers_menubtn.setText("Register Users");
        registerUsers_menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registerUsers_menubtnActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Z003", 1, 36)); // NOI18N
        jLabel2.setText("Welcome");

        communications_menubtn.setText("Communications");
        communications_menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communications_menubtnActionPerformed(evt);
            }
        });

        viewAdmins_menubtn.setText("View Admins");
        viewAdmins_menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewAdmins_menubtnActionPerformed(evt);
            }
        });

        logout_menubtn.setText("Logout");
        logout_menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_menubtnActionPerformed(evt);
            }
        });

        settings_menubtn.setText("settings");
        settings_menubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settings_menubtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jLabel2))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(welcomeuser))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(registerUsers_menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(rigsterAdmins_menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(viewUsers_menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(communications_menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(viewAdmins_menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(logout_menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(settings_menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(58, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(registerUsers_menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rigsterAdmins_menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(viewUsers_menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(viewAdmins_menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(communications_menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(settings_menubtn, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logout_menubtn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(welcomeuser)
                .addGap(22, 22, 22))
        );

        jLabel11.setFont(new java.awt.Font("Z003", 1, 36)); // NOI18N
        jLabel11.setText("Register New Admins");

        register_adminbtn.setText("Register");
        register_adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                register_adminbtnActionPerformed(evt);
            }
        });

        jLabel1.setText("username");

        jLabel3.setText("password");

        password_admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password_adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(username_admin)
                    .addComponent(password_admin, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(register_adminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(354, 354, 354))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(342, 342, 342))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(111, 111, 111)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(username_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(password_admin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addComponent(register_adminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("admins register", jPanel2);

        jPanel6.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel6.setFont(new java.awt.Font("Z003", 1, 36)); // NOI18N
        jLabel6.setText("Register New Users");

        user_registerbtn.setText("Register");
        user_registerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                user_registerbtnActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        jLabel7.setText("Username");

        jLabel8.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        jLabel8.setText("Password");

        jLabel9.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        jLabel9.setText("Email");

        gender.add(male_rbtn);
        male_rbtn.setSelected(true);
        male_rbtn.setText("Male");
        male_rbtn.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        gender.add(female_rbtn);
        female_rbtn.setText("Female");
        female_rbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                female_rbtnActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        jLabel10.setText("Gender");

        password2_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                password2_inputActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Z003", 1, 24)); // NOI18N
        jLabel5.setText("Confirm Password");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(userName_reg, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(476, 476, 476)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(user_registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(male_rbtn)
                                .addGap(60, 60, 60)
                                .addComponent(female_rbtn))))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGap(321, 321, 321)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(useremail_reg)
                            .addComponent(password2_input, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                            .addComponent(password_reg))))
                .addContainerGap(349, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(113, 113, 113)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(userName_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(password_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password2_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(useremail_reg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(male_rbtn)
                    .addComponent(female_rbtn))
                .addGap(13, 13, 13)
                .addComponent(user_registerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jTabbedPane1.addTab("users register", jPanel6);

        users_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "id", "username", "password", "useremail", "gender"
            }
        ));
        jScrollPane1.setViewportView(users_table);

        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        userid_input.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userid_inputActionPerformed(evt);
            }
        });

        jLabel4.setText("Userid");

        jButton7.setText("view users");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1054, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userid_input, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 464, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jLabel4)
                    .addComponent(userid_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jTabbedPane1.addTab("view users", jPanel3);

        admins_table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "id", "username", "password"
            }
        ));
        jScrollPane2.setViewportView(admins_table);

        viewadmins_btn.setText("view admins");
        viewadmins_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewadmins_btnActionPerformed(evt);
            }
        });

        deleteadmin_btn.setText("delete");
        deleteadmin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteadmin_btnActionPerformed(evt);
            }
        });

        jLabel12.setText("admin id");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1063, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewadmins_btn)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(deleteadmin_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(adminid_input, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(viewadmins_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deleteadmin_btn)
                    .addComponent(jLabel12)
                    .addComponent(adminid_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8))
        );

        jTabbedPane1.addTab("view admins", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1075, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("communications", jPanel8);

        jLabel13.setText("Current User Name : ");

        jLabel14.setFont(new java.awt.Font("Z003", 1, 48)); // NOI18N
        jLabel14.setText("Profile Settings");

        jLabel15.setText("Password : ");

        current_username.setEditable(false);
        current_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                current_usernameActionPerformed(evt);
            }
        });

        update_adminpassbtn.setText("Update Password");
        update_adminpassbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                update_adminpassbtnActionPerformed(evt);
            }
        });

        delete_adminbtn.setBackground(new java.awt.Color(255, 51, 51));
        delete_adminbtn.setFont(new java.awt.Font("Cantarell", 1, 15)); // NOI18N
        delete_adminbtn.setForeground(new java.awt.Color(255, 255, 255));
        delete_adminbtn.setText("Delete Account");
        delete_adminbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete_adminbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(current_username)
                    .addComponent(current_password, javax.swing.GroupLayout.DEFAULT_SIZE, 197, Short.MAX_VALUE))
                .addGap(68, 68, 68)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(update_adminpassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete_adminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(352, 352, 352))
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(295, 295, 295)
                .addComponent(jLabel14)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addGap(92, 92, 92)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(update_adminpassbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(current_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(delete_adminbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(current_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(269, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("settings", jPanel9);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1075, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerUsers_menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registerUsers_menubtnActionPerformed
        // TODO add your handling code here:

        jTabbedPane1.setSelectedIndex(1);
    }//GEN-LAST:event_registerUsers_menubtnActionPerformed

    private void viewUsers_menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewUsers_menubtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(2);
    }//GEN-LAST:event_viewUsers_menubtnActionPerformed

    private void rigsterAdmins_menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rigsterAdmins_menubtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(0);
    }//GEN-LAST:event_rigsterAdmins_menubtnActionPerformed

    private void female_rbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_female_rbtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_female_rbtnActionPerformed

    private void get_current_users(){
        try {
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM netpackt.users");
            
            ResultSet rs = stmt.executeQuery();
            clearTableModel();
            while (rs.next()) {
                    int userId = rs.getInt("id");
                    String username = rs.getString("username");
                    String password = rs.getString("password");
                    String useremail = rs.getString("useremail");
                    int gender = rs.getInt("gender");

                    Object[] rowData = {userId, username, password, useremail, gender};
                    DefaultTableModel model = (DefaultTableModel) users_table.getModel();
                    model.addRow(rowData);
            }
        }
        catch(SQLException ex){
            
        }
        
    }
    private void delete_user(int userid){
        try{
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM netpackt.users where id = ?");
            stmt.setInt(1, userid);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                PreparedStatement delete_stmt = con.prepareStatement("DELETE FROM netpackt.users where id = ?");
                delete_stmt.setInt(1, userid);
                delete_stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "USER DELETED");
                get_current_users();
            }
            else{
                JOptionPane.showMessageDialog(this, "inccorect user id or user not found");
            }
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
    }
    
    private void clearTableModel() {
        DefaultTableModel model = (DefaultTableModel) users_table.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    private void user_registerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_user_registerbtnActionPerformed
        // TODO add your handling code here:

        String username = userName_reg.getText();
        String password = password_reg.getText();
        String email = useremail_reg.getText();
        String password_confirm = password2_input.getText();
        if(!username.isEmpty() && !password.isEmpty() && !email.isEmpty() && !password_confirm.isBlank() ){
            if (password.equals(password_confirm)){
                var gender = 0;
                if (female_rbtn.isSelected()){
                    gender = 0;
                }
                else{
                    gender = 1;
                }
                int reg_user = register_user(username, password, email, gender);
                if (reg_user == 0){
                    userName_reg.setText("");
                    password_reg.setText("");
                    useremail_reg.setText("");
                    JOptionPane.showMessageDialog(this, "user inserted succsessfully");
                }else if(reg_user == -1){
                    JOptionPane.showMessageDialog(this, "user already exists");
                }
                else{
                    JOptionPane.showMessageDialog(this, "An Error encounterd");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Password and password confirmation are diffrent");
            }
        }else{
            JOptionPane.showMessageDialog(this, "cannot leave inputs blank");
        }

    }//GEN-LAST:event_user_registerbtnActionPerformed

    private void password_adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password_adminActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password_adminActionPerformed

    private void register_adminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_register_adminbtnActionPerformed
        // TODO add your handling code here:

        String username = username_admin.getText();
        String password = password_admin.getText();
        if(!username.isEmpty() && !password.isEmpty()){
            int reg_admin = register_admin(username, password);
            if (reg_admin == 0){
                username_admin.setText("");
                password_admin.setText("");

                JOptionPane.showMessageDialog(this, "admin inserted succsessfully");
            }else if(reg_admin == -1){
                JOptionPane.showMessageDialog(this, "admin already exists");
            }
            else{
                JOptionPane.showMessageDialog(this, "An Error encounterd");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "cannot leave inputs blank");
        }
    }//GEN-LAST:event_register_adminbtnActionPerformed

    private void userid_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userid_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userid_inputActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        get_current_users();
    }//GEN-LAST:event_jButton7ActionPerformed
  
    

    public admindashboard(Connection con , JRadioButton female_rbtn, ButtonGroup gender, JButton jButton2, JButton jButton3, JButton jButton4, JButton jButton5, JButton jButton6, JButton jButton7, JLabel jLabel1, JLabel jLabel10, JLabel jLabel11, JLabel jLabel2, JLabel jLabel3, JLabel jLabel4, JLabel jLabel5, JLabel jLabel6, JLabel jLabel7, JLabel jLabel8, JLabel jLabel9, JPanel jPanel1, JPanel jPanel2, JPanel jPanel3, JPanel jPanel4, JPanel jPanel5, JPanel jPanel6, JScrollPane jScrollPane1, JTabbedPane jTabbedPane1, JRadioButton male_rbtn, JTextField password_admin, JTextField password_reg, JButton register_adminbtn, JButton register_userpanelbtn, JTextField userName_reg, JButton user_registerbtn, JTextField useremail_reg, JTextField userid_input, JTextField username_admin, JTable users_table, JButton viewusers_btn) throws HeadlessException {
        this.con = con;
        
        this.female_rbtn = female_rbtn;
        this.gender = gender;
        this.logout_menubtn = jButton2;
        this.rigsterAdmins_menubtn = jButton3;
        this.viewAdmins_menubtn = jButton4;
        this.communications_menubtn = jButton5;
        this.jButton6 = jButton6;
        this.jButton7 = jButton7;
        this.jLabel1 = jLabel1;
        this.jLabel10 = jLabel10;
        this.jLabel11 = jLabel11;
        this.jLabel2 = jLabel2;
        this.jLabel3 = jLabel3;
        this.jLabel4 = jLabel4;
        this.welcomeuser = jLabel5;
        this.jLabel6 = jLabel6;
        this.jLabel7 = jLabel7;
        this.jLabel8 = jLabel8;
        this.jLabel9 = jLabel9;
        this.jPanel1 = jPanel1;
        this.jPanel2 = jPanel2;
        this.jPanel3 = jPanel3;
        this.jPanel4 = jPanel4;
        this.jPanel5 = jPanel5;
        this.jPanel6 = jPanel6;
        this.jScrollPane1 = jScrollPane1;
        this.jTabbedPane1 = jTabbedPane1;
        this.male_rbtn = male_rbtn;
        this.password_admin = password_admin;
        this.password_reg = (JPasswordField) password_reg;
        this.register_adminbtn = register_adminbtn;
        this.registerUsers_menubtn = register_userpanelbtn;
        this.userName_reg = userName_reg;
        this.user_registerbtn = user_registerbtn;
        this.useremail_reg = useremail_reg;
        this.userid_input = userid_input;
        this.username_admin = username_admin;
        this.users_table = users_table;
        this.viewUsers_menubtn = viewusers_btn;
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String userid = userid_input.getText();    
        if (!userid.isBlank()){
            int useridcasted = Integer.parseInt(userid);
            userid_input.setText("");
            delete_user(useridcasted);
        }
        else{
            JOptionPane.showMessageDialog(this, "cannot leave inputs blank");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void logout_menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_menubtnActionPerformed
        // TODO add your handling code here:
        login newFrame = new login(); 
        newFrame.setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_menubtnActionPerformed
    private void clearTableModel_admins() {
        DefaultTableModel model = (DefaultTableModel) admins_table.getModel();
        int rowCount = model.getRowCount();
        for (int i = rowCount - 1; i >= 0; i--) {
            model.removeRow(i);
        }
    }
    private void view_admins(){
        try {
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM netpackt.admins");
            
            ResultSet rs = stmt.executeQuery();
            clearTableModel_admins();
            while (rs.next()) {
                    int userId = rs.getInt("id");
                    String username = rs.getString("username");
                    String password = rs.getString("password");

                    Object[] rowData = {userId, username, password};
                    DefaultTableModel model = (DefaultTableModel) admins_table.getModel();
                    model.addRow(rowData);
            }
        }
        catch(SQLException ex){
            
        }
    }
    private void delete_admin(int userid){
        try{
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM netpackt.admins where id = ?");
            stmt.setInt(1, userid);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                PreparedStatement delete_stmt = con.prepareStatement("DELETE FROM netpackt.admins where id = ?");
                delete_stmt.setInt(1, userid);
                delete_stmt.executeUpdate();
                JOptionPane.showMessageDialog(this, "admin DELETED");
                view_admins();
            }
            else{
                JOptionPane.showMessageDialog(this, "inccorect admin id or user not found");
            }
        }
        catch(SQLException ex){
            System.out.println(ex);
        }
    }
    private void viewadmins_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewadmins_btnActionPerformed
        // TODO add your handling code here:
        view_admins();
    }//GEN-LAST:event_viewadmins_btnActionPerformed

    private void deleteadmin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteadmin_btnActionPerformed
        // TODO add your handling code here:
        String userid = adminid_input.getText();    
        if (!userid.isBlank()){
            int useridcasted = Integer.parseInt(userid);
            try{
                PreparedStatement stmt = con.prepareStatement("SELECT username FROM netpackt.admin where id  = ?");
                stmt.setInt(1, useridcasted);
                ResultSet rs = stmt.executeQuery();
                if(rs.next()){
                    String username_tobe_deleted = rs.getString("username");
                    if (username_tobe_deleted.equals( cuurentusername)){
                        adminid_input.setText("");
                        JOptionPane.showMessageDialog(this, "if you want to delete current account go to settings");
                    }
                    else{
                        adminid_input.setText("");
                        delete_admin(useridcasted);
                    }
                }
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error deleting admin account");
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "cannot leave inputs blank");
        }
    }//GEN-LAST:event_deleteadmin_btnActionPerformed

    private void update_adminpassbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_update_adminpassbtnActionPerformed
        // TODO add your handling code here:
        String newpass = current_password.getText();
        if(!newpass.isEmpty()){
            String hashednewpass = MD5Hashing.md5(newpass);
            try{
                PreparedStatement stmt = con.prepareStatement("UPDATE netpackt.admins set password = ? WHERE username = ?");
                stmt.setString(1, hashednewpass);
                stmt.setString(2, cuurentusername);
                stmt.executeUpdate();
                current_password.setText("");
                JOptionPane.showMessageDialog(this, "Your Password has been changed, don't forget to login with the new password next time.");
            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error updating the password");
            }   
        }else{
            JOptionPane.showMessageDialog(this, "cannot leave inputs blank");
        }
    }//GEN-LAST:event_update_adminpassbtnActionPerformed

    private void current_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_current_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_current_usernameActionPerformed

    private void settings_menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settings_menubtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(5);
    }//GEN-LAST:event_settings_menubtnActionPerformed

    private void delete_adminbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete_adminbtnActionPerformed
        // TODO add your handling code here:
        try{
                PreparedStatement stmt = con.prepareStatement("SELECT * FROM netpackt.admins where username != ?");
                stmt.setString(1, cuurentusername);
                ResultSet rs = stmt.executeQuery();
                if (rs.next()){
                    PreparedStatement delete_stmt = con.prepareStatement("DELETE FROM netpackt.admins WHERE username = ?");
                    delete_stmt.setString(1, cuurentusername);
                    delete_stmt.executeUpdate();
                    JOptionPane.showMessageDialog(this, "this admin account has been deleted you will be redirected to the login");
                    login newFrame = new login(); 
                    newFrame.setVisible(true);
                    dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "There must be at least one admin for the system");

                }

            }catch(SQLException ex){
                JOptionPane.showMessageDialog(this, "Error Deleting admin account");
            }
    }//GEN-LAST:event_delete_adminbtnActionPerformed

    private void viewAdmins_menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewAdmins_menubtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(3);
    }//GEN-LAST:event_viewAdmins_menubtnActionPerformed

    private void communications_menubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communications_menubtnActionPerformed
        // TODO add your handling code here:
        jTabbedPane1.setSelectedIndex(4);
    }//GEN-LAST:event_communications_menubtnActionPerformed

    private void password2_inputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_password2_inputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_password2_inputActionPerformed
    private int register_user(String username, String password, String email, int gender){
        int result = -1;
        try{
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM netpackt.users Where useremail = ?");
            stmt.setString(1, email);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                result = -1;
            }
            else{
                try{
                    //inserting new user in the database
                    PreparedStatement stmt_reg = con.prepareStatement("INSERT INTO netpackt.users (username, password, useremail, gender) values (?,?,?,?)");
                    stmt_reg.setString(1, username);
                    String HashedPass = MD5Hashing.md5(password);
                    stmt_reg.setString(2, HashedPass);
                    stmt_reg.setString(3, email);
                    stmt_reg.setInt(4, gender);
                    stmt_reg.executeUpdate();
                    // generating public and private keys for currently inserted user
                    RSA keys = new RSA();
                    keys.generateKeysNew(username);
                    result = 0;
                }catch(SQLException ex){
                    
                    result = 1;
                }
                
            }
        }
        catch(SQLException ex){
            result = 1;
        }
        return result;
    }
     private int register_admin(String username, String password){
        int result = -1;
        try{
            PreparedStatement stmt = con.prepareStatement("SELECT * FROM netpackt.admins Where username = ?");
            stmt.setString(1, username);
            ResultSet rs = stmt.executeQuery();
            if (rs.next()) {
                result = -1;
            }
            else{
                try{
                    PreparedStatement stmt_reg = con.prepareStatement("INSERT INTO netpackt.admins (username, password) values (?,?)");
                    stmt_reg.setString(1, username);
                    String HashedPass = MD5Hashing.md5(password);
                    stmt_reg.setString(2, HashedPass);
                    stmt_reg.executeUpdate();
                    result = 0;
                }catch(SQLException ex){
                    
                    result = 1;
                }
                
            }
        }
        catch(SQLException ex){
            result = 1;
        }
        return result;
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(admindashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new admindashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adminid_input;
    private javax.swing.JTable admins_table;
    private javax.swing.JButton communications_menubtn;
    private javax.swing.JPasswordField current_password;
    private javax.swing.JTextField current_username;
    private javax.swing.JButton delete_adminbtn;
    private javax.swing.JButton deleteadmin_btn;
    private javax.swing.JRadioButton female_rbtn;
    private javax.swing.ButtonGroup gender;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton logout_menubtn;
    private javax.swing.JRadioButton male_rbtn;
    private javax.swing.JPasswordField password2_input;
    private javax.swing.JTextField password_admin;
    private javax.swing.JPasswordField password_reg;
    private javax.swing.JButton registerUsers_menubtn;
    private javax.swing.JButton register_adminbtn;
    private javax.swing.JButton rigsterAdmins_menubtn;
    private javax.swing.JButton settings_menubtn;
    private javax.swing.JButton update_adminpassbtn;
    private javax.swing.JTextField userName_reg;
    private javax.swing.JButton user_registerbtn;
    private javax.swing.JTextField useremail_reg;
    private javax.swing.JTextField userid_input;
    private javax.swing.JTextField username_admin;
    private javax.swing.JTable users_table;
    private javax.swing.JButton viewAdmins_menubtn;
    private javax.swing.JButton viewUsers_menubtn;
    private javax.swing.JButton viewadmins_btn;
    private javax.swing.JLabel welcomeuser;
    // End of variables declaration//GEN-END:variables
}
